build:
  image: bitwalker/alpine-elixir-phoenix:2.0
  commands:
    - apk update
    - apk add postgresql-client
    - mix local.hex --force && mix local.rebar --force
    - mix do deps.get, deps.compile
    - MIX_ENV=test mix ecto.create ecto.migrate -r Blabber.Repo
    - mix test

cache:
  mount:
    - deps
    - _build

compose:
  database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
